name: flutter_sandbox
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.9.0
  cloud_functions: ^3.3.9
  scratcher: ^2.3.0
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  geolocator: ^9.0.2
  google_polyline_algorithm: ^3.1.0
  gap: ^2.0.1
  faker: ^2.1.0
  freezed: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/